name: Info Workflow

on:
  push:
    branches:
      - main

jobs:
  info-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log commit hash
        run: |
          echo "Commit hash: ${{ github.sha }}"
