name: Info Workflow

on:
  push:
    branches:
      - main

jobs:
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log commit hash
      run: |
        echo "Commit hash: ${{ github.sha }}"
